### PR TITLE
fix: get correct exit code from npm publish/view

### LINKED ISSUE #417: "syntax error: invalid arithmetic operator" in log after `npm publish`
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The "Release Integration > Publish" action includes the `npm publish` command. The corresponding action log contains the following error:

```
/home/runner/work/_temp/570d07ac-66bd-47e2-805d-030313533c8a.sh: line 14: [[: + semver@7.6.0
0: syntax error: invalid arithmetic operator (error token is "@7.6.0
0")
```

Example: 

https://github.com/npm/node-semver/actions/runs/7788106733/job/21236934252

image

### Expected Behavior

No error in log

### Steps To Reproduce

Run "Release Integration > Publish" workflow

https://github.com/npm/node-semver/blob/main/.github/workflows/release-integration.yml

### Environment

- github.com

### PR DESCRIPTION
**Pull request by lukekarrys**
Closes #417

### CODE REVIEW

File: tap-snapshots/test/apply/source-snapshots.js.test.cjs [hunk 1]
```diff
@@ -889,17 +889,10 @@ jobs:
...
-              echo 0
-            else
-              echo 1
-            fi
-          }
-
           for release in $(echo $RELEASES | jq -r '.[] | @base64'); do
-            SPEC="$(echo "$release" | base64 --decode | jq -r .pkgName)@$(echo "$release" | base64 --decode | jq -r .version)"
-            STATUS=$(each_release "$SPEC")
+            SPEC=$(echo "$release" | base64 --decode | jq -r .pkgName)@$(echo "$release" | base64 --decode | jq -r .version)"
```
Comment (lukekarrys) [inline tap-snapshots/test/apply/source-snapshots.js.test.cjs:893]: Missing a quote here

**Review by wraithgar — APPROVED** [review]
