### PR TITLE
fix: prefer upstream over origin when getting remote

### LINKED ISSUE #363: package scripts should use `upstream`, not `origin`, to set repository.url from git
The repository URLs are based on assuming that `origin` is the authoritative url and updates `package.json` based on this. In the case of this repo, it causes tests to fail locally.

This should be expecting `origin` to be the default branch to push/pull and `upstream` to be the authoritative repo because:

- This is the setup recommended by GitHub https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/configuring-a-remote-repository-for-a-fork
- This is what happens if you clone a repo "for contributing to the upstream project" in GitHub desktop
- This is what happens if you clone a repo in VSCode, try to push to that repo, and choose to create a fork when it prompts you to.

Per @lukekarrys in https://github.com/npm/template-oss/issues/338#issuecomment-1719980875
> @rotu that is due to the autodetection of the `origin` by git. If you've forked the repo make sure that `npm/template-oss` is the `origin` and the remote url for your fork is named something different (eg `fork`):
> 
> ```
> ❯ git remotes
> fork	git@github.com:lukekarrys/template-oss.git (fetch)
> fork	git@github.com:lukekarrys/template-oss.git (push)
> origin	git@github.com:npm/template-oss.git (fetch)
> origin	git@github.com:npm/template-oss.git (push)
> ```

### PR DESCRIPTION
**Pull request by lukekarrys**
Fixes #363

### CODE REVIEW

File: lib/util/git.js [hunk 1]
```diff
@@ -19,9 +19,9 @@ const tryGit = async (path, ...args) => {
 
 // parse a repo from a git origin into a format
 // for a package.json#repository object
-const getUrl = async (path) => {
+const getRemoteUrl = async (path, remote) => {
   try {
-    const urlStr = await tryGit(path, 'remote', 'get-url', 'origin')
+    const urlStr = await tryGit(path, 'remote', 'get-url', remote)
```
Comment (wraithgar) [inline lib/util/git.js:24]:
```sh
~/D/n/c/b/main (latest|✔) $ git remote get-url upstream
error: No such remote 'upstream'
~/D/n/c/b/main (latest|✔) $ echo $status
2
```
does this gracefully handle if it's missing?

Comment (lukekarrys) [reply lib/util/git.js:24]: yeah, it will return undefined if its missing and then move to the next remote

**Review by wraithgar — APPROVED** [review]

**Comment by rotu** [comment]
woohoo! thank you!
